### ISSUE TITLE
You forgot to mention the api key!

### ISSUE THREAD

**Issue by darkelement1987** [ultrafunkamsterdam/PokemonGoMap-Website#1]
Didn't work at all until i changed the api key url within the index.html file

`<script defer src="https://maps.googleapis.com/maps/api/js?key=apikeygoeshere&amp;callback=initMap&amp;libraries=places,geometry"></script>`

It now shows the map (javascript error before this) but doesn't show pokemon yet.

edit: I now realise i was using the original server (see link below) instead of your fork, don't know if that matters anything? What's the difference between your fork and the original?

https://github.com/PokemonGoMap/PokemonGo-Map

**Comment by ultrafunkamsterdam** [comment]
Thanks, i just updated the README.md. 

The difference is.. when you run a PokemonGo-Map server (https://github.com/PokemonGoMap/PokemonGo-Map) which is accessible from the web. You could upload this  files to any webhost serving only static content. It interacts with your backend, but users can not change search positions and such. So you could create a website where multiple users/friends can look and search for pokemon, but not control your threads.

**Comment by darkelement1987** [comment]
I get the point, and i did everything right, it's just not working, the map shows, but without the pokemon (which show perfectly fine on my own site) 

There we're even .js files still containing your own base url after changing everything the readme mentioned. (see screenshot)

Check it out for yourself:

My files:
http://tjielup.nl/staticpage.zip

My server: http://map.tjielup.nl:5000

Screenshot:

http://www.tjielup.nl/screenshot.png

The static page:

http://www.tjielup.nl/pokemon/

Look's like its not grabbing anything from the db
